import Header from './components/Header';
import Footer from './components/Footer';
import './App.css';

function App() {
  return (
    <div className="App">
      <Header />
      <h2>"Hello Knitpoppy!"</h2>
      <p>I've been using it nonstop since I got it. I love that it's a little more on the "smaller" side as I am trying to get use to carrying less items in my bags. It fits all the necessities! Phone, keys, wallet, AirPods, chapstick and hand sanitizer/lotion. I've also managed to carry my iPad with me on a few occasions and a make bag. So it definitely will carry what you need! It seems pretty sturdy and I think it will last me a while, which I hope because I really like this bag!</p>
      <p>I've been using it nonstop since I got it. I love that it's a little more on the "smaller" side as I am trying to get use to carrying less items in my bags. It fits all the necessities! Phone, keys, wallet, AirPods, chapstick and hand sanitizer/lotion. I've also managed to carry my iPad with me on a few occasions and a make bag. So it definitely will carry what you need! It seems pretty sturdy and I think it will last me a while, which I hope because I really like this bag!</p><p>I've been using it nonstop since I got it. I love that it's a little more on the "smaller" side as I am trying to get use to carrying less items in my bags. It fits all the necessities! Phone, keys, wallet, AirPods, chapstick and hand sanitizer/lotion. I've also managed to carry my iPad with me on a few occasions and a make bag. So it definitely will carry what you need! It seems pretty sturdy and I think it will last me a while, which I hope because I really like this bag!</p><p>I've been using it nonstop since I got it. I love that it's a little more on the "smaller" side as I am trying to get use to carrying less items in my bags. It fits all the necessities! Phone, keys, wallet, AirPods, chapstick and hand sanitizer/lotion. I've also managed to carry my iPad with me on a few occasions and a make bag. So it definitely will carry what you need! It seems pretty sturdy and I think it will last me a while, which I hope because I really like this bag!</p><p>I've been using it nonstop since I got it. I love that it's a little more on the "smaller" side as I am trying to get use to carrying less items in my bags. It fits all the necessities! Phone, keys, wallet, AirPods, chapstick and hand sanitizer/lotion. I've also managed to carry my iPad with me on a few occasions and a make bag. So it definitely will carry what you need! It seems pretty sturdy and I think it will last me a while, which I hope because I really like this bag!</p><p>I've been using it nonstop since I got it. I love that it's a little more on the "smaller" side as I am trying to get use to carrying less items in my bags. It fits all the necessities! Phone, keys, wallet, AirPods, chapstick and hand sanitizer/lotion. I've also managed to carry my iPad with me on a few occasions and a make bag. So it definitely will carry what you need! It seems pretty sturdy and I think it will last me a while, which I hope because I really like this bag!</p><p>I've been using it nonstop since I got it. I love that it's a little more on the "smaller" side as I am trying to get use to carrying less items in my bags. It fits all the necessities! Phone, keys, wallet, AirPods, chapstick and hand sanitizer/lotion. I've also managed to carry my iPad with me on a few occasions and a make bag. So it definitely will carry what you need! It seems pretty sturdy and I think it will last me a while, which I hope because I really like this bag!</p>
      <Footer />
    </div>
  );
}

export default App;
